# Generated by Django 5.2.4 on 2025-07-20 05:24

from django_ckeditor_5.fields import CKEditor5Field

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=CKEditor5Field('Content'),  # Changed from RichTextField
        ),
    ]
