# Generated by Django 5.2.4 on 2025-07-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('meaning', models.TextField(default='Meaning not available')),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Buddhism', 'Buddhism'), ('Other', 'Other')], max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default='Boy', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='baby_images/')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
