# Generated by Django 5.2.4 on 2025-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyname',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babyname',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='babyname',
            name='syllables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='religion',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='babyname',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
